#include<stdio.h>
int main(){
	
	printf("            CARGANDO\n");
	printf("|                           |\n");
	printf("|                           |\n");
	printf("|                           |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|/                          |\n");
	printf("|                           |\n");
	printf("|                           |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|//                         |\n");
	printf("|/                          |\n");
	printf("|                           |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|///                        |\n");
	printf("|//                         |\n");
	printf("|/                          |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO\n");
	printf("|////                       |\n");
	printf("|///                        |\n");
	printf("|//                         |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|/////                      |\n");
	printf("|////                       |\n");
	printf("|///                        |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|//////                     |\n");
	printf("|/////                      |\n");
	printf("|////                       |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|///////                    |\n");
	printf("|//////                     |\n");
	printf("|/////                      |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO\n");
	printf("|////////                   |\n");
	printf("|///////                    |\n");
	printf("|//////                     |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|/////////                  |\n");
	printf("|////////                   |\n");
	printf("|///////                    |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|//////////                 |\n");
	printf("|/////////                  |\n");
	printf("|////////                   |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|///////////                |\n");
	printf("|//////////                 |\n");
	printf("|/////////                  |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO\n");
	printf("|////////////               |\n");
	printf("|///////////                |\n");
	printf("|//////////                 |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|/////////////              |\n");
	printf("|////////////               |\n");
	printf("|///////////                |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|//////////////             |\n");
	printf("|/////////////              |\n");
	printf("|////////////               |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|///////////////            |\n");
	printf("|//////////////             |\n");
	printf("|/////////////              |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO\n");
	printf("|////////////////           |\n");
	printf("|///////////////            |\n");
	printf("|//////////////             |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|/////////////////          |\n");
	printf("|////////////////           |\n");
	printf("|///////////////            |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|//////////////////         |\n");
	printf("|/////////////////          |\n");
	printf("|////////////////           |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|///////////////////        |\n");
	printf("|//////////////////         |\n");
	printf("|/////////////////          |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO\n");
	printf("|////////////////////       |\n");
	printf("|///////////////////        |\n");
	printf("|//////////////////         |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|/////////////////////      |\n");
	printf("|////////////////////       |\n");
	printf("|///////////////////        |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|//////////////////////     |\n");
	printf("|/////////////////////      |\n");
	printf("|////////////////////       |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|///////////////////////    |\n");
	printf("|//////////////////////     |\n");
	printf("|/////////////////////      |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|////////////////////////   |\n");
	printf("|///////////////////////    |\n");
	printf("|//////////////////////     |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|/////////////////////////  |\n");
	printf("|////////////////////////   |\n");
	printf("|///////////////////////    |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. . .\n");
	printf("|////////////////////////// |\n");
	printf("|/////////////////////////  |\n");
	printf("|////////////////////////   |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO\n");
	printf("|///////////////////////////|\n");
	printf("|////////////////////////// |\n");
	printf("|/////////////////////////  |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO.\n");
	printf("|///////////////////////////|\n");
	printf("|///////////////////////////|\n");
	printf("|////////////////////////// |\n");
	sleep(1);
	system("cls");
	printf("            CARGANDO. .\n");
	printf("|///////////////////////////|\n");
	printf("|///////////////////////////|\n");
	printf("|///////////////////////////|\n");
	sleep(1);
	system("cls");
	printf("        carga completa\n");
	
	return 0;
}
